backend:
  name: git-gateway
  branch: main

locale: 'de'

media_folder: "uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "datetime" }
      - { label: "Bild", name: "thumbnail", widget: "image" }
      - { label: "PDF Anhang", name: "pdf", widget: "file", required: false }
      - { label: "Text", name: "body", widget: "markdown" }

  - name: "seiten"
    label: "Seiten"
    files:
      - label: "Über uns"
        name: "ueberuns"
        file: "content/ueber-uns.md"
        fields:
          - { label: "Inhalt", name: "body", widget: "markdown" }
